
name: IRAF macOS build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - name: macOS 12 (Intel)
            os: macos-12

          - name: macOS 14 (M1)
            os: macos-14

    env:
      TERM: ansi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup XQuartz on macOS
        run: |
          wget https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.1/XQuartz-2.8.1.dmg
          sudo hdiutil attach XQuartz-2.8.1.dmg
          sudo installer -package /Volumes/XQuartz-2.8.1/XQuartz.pkg -target /
          sudo rm -f /usr/local/include/tcl.h

      - name: Build package
        run: |
           make -j 4

      - name: Locally test package installation
        run: |
          sudo installer -pkg iraf-*64.pkg -target / -verbose
          /usr/local/lib/iraf/test/run_tests /usr/local/lib/iraf/test/noao.astutil.md

      - name: Copy file via ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add -v - <<< "${{ secrets.SSH_KEY }}"
          scp -o StrictHostKeyChecking=no iraf-*64.pkg iraf@olebole.net:dist/
