
name: IRAF macOS build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - name: arm64
            os: macos-latest
            arch: arm64

          - name: x86_64
            os: macos-latest
            arch: x86_64

    env:
      TERM: ansi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup XQuartz on macOS
        run: |
          wget https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.1/XQuartz-2.8.1.dmg
          sudo hdiutil attach XQuartz-2.8.1.dmg
          sudo installer -package /Volumes/XQuartz-2.8.1/XQuartz.pkg -target /
          sudo rm -f /usr/local/include/tcl.h

      - name: Setup required build tools from brew (ImageMagic for the moment)
        run: |
          brew install imagemagick
          
      - name: Build package
        run: |
           make -j 4 MACARCH=${{ matrix.arch }}

      - name: Locally test package installation
        run: |
          cp iraf-*.pkg /tmp
          sudo installer -pkg /tmp/iraf-*.pkg -target / -verbose
          /usr/local/lib/iraf/test/run_tests /usr/local/lib/iraf/test/noao.astutil.md

      - name: Copy file via ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add -v - <<< "${{ secrets.SSH_KEY }}"
          scp -o StrictHostKeyChecking=no iraf-*.pkg iraf@olebole.net:dist/
