
name: IRAF macOS build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14

    env:
      iraf: ${{ github.workspace }}/iraf/
      TERM: ansi
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout IRAF
        uses: actions/checkout@v3
        with:
          repository: iraf-community/iraf
          path: ${{ env.iraf }}

      - name: Checkout x11iraf
        uses: actions/checkout@v3
        with:
          repository: iraf-community/x11iraf
          path: x11iraf

      - name: Setup XQuartz on macOS
        run: |
          wget https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.1/XQuartz-2.8.1.dmg
          sudo hdiutil attach XQuartz-2.8.1.dmg
          sudo installer -package /Volumes/XQuartz-2.8.1/XQuartz.pkg -target /
          sudo rm -f /usr/local/include/tcl.h

      - name: Build IRAF
        run: |
           # IRAFARCH=macos64 CFLAGS="-O2" make -C ${{ env.iraf }}

      - name: Run IRAF tests
        run: |
           #  make -C ${{ env.iraf }} test

      - name: Build x11iraf
        run: |
          make -C x11iraf

      - name: Installation
        run: |
          mkdir install
          #make -C ${{ env.iraf }} DESTDIR=`pwd`/install install
          make -C x11iraf DESTDIR=`pwd`/install install

      - name: Create distribution file
        run: |
          # tar cvf iraf-v2.17.1_macos.tar.gz -C install .
          pkgbuild --identifier org.iraf-community.iraf.app --root install --install-location / iraf0.pkg
          productbuild --distribution iraf_distribution.plist --resources . --package-path iraf0.pkg iraf.pkg

      - name: Copy file via ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add -v - <<< "${{ secrets.SSH_KEY }}"
          #scp -o StrictHostKeyChecking=no iraf-v2.17.1_macos.tar.gz iraf@olebole.net:dist/
          scp -o StrictHostKeyChecking=no iraf.pkg iraf@olebole.net:dist/
